### ISSUE TITLE
Could not resolve host: mirrors.163.com; Unknown error

### ISSUE THREAD

**Issue by bochuxt** [rootsongjc/kubernetes-vagrant-centos-cluster#11]
```
node1: http://mirrors.163.com/centos/7/extras/x86_64/Packages/etcd-3.2.15-1.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node1: Trying other mirror.
    node
node1: 
    node1: Error downloading packages:
    node1:   etcd-3.2.15-1.el7.x86_64: [Errno 256] No more mirrors to try.
    node1: /tmp/vagrant-shell: line 63: /etc/etcd/etcd.conf: No such file or directory
    node1: cat: /etc/etcd/etcd.conf: No such file or directory
    node1: create network config in etcd
    node1: /tmp/vagrant-shell: line 79: /etc/etcd/etcd-init.sh: No such file or directory
    node1: chmod: cannot access ‘/etc/etcd/etcd-init.sh’: No such file or directory
    node1: start etcd...
    node1: Failed to execute operation: No such file or directory
    node1: Failed to start etcd.service: Unit not found.
    node1: create kubernetes ip range for flannel on 172.33.0.0/16
    node1: /tmp/vagrant-shell: line 91: /etc/etcd/etcd-init.sh: No such file or directory
    node1: /tmp/vagrant-shell: line 92: etcdctl: command not found
    node1: /tmp/vagrant-shell: line 93: etcdctl: command not found
    node1: install flannel...
    node1: Loaded plugins: fastestmirror
```
