### ISSUE TITLE
/proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory

### ISSUE THREAD

**Issue by bochuxt** [rootsongjc/kubernetes-vagrant-centos-cluster#12]
```
de2: 
    node2: Complete!
    node2: sync time
    node2: Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
    node2: disable selinux
    node2: enable iptable kernel parameter
    node2: net.ipv4.ip_forward = 1
    node2: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory
    node2: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
    node2: set host name resolution
```
