### ISSUE TITLE
安装过程卡死，copy pem, token files后，命令行输出“node1: kubernetes/LICENSES“，卡死。

### ISSUE THREAD

**Issue by lefeudelavie** [rootsongjc/kubernetes-vagrant-centos-cluster#80]
# Environment

- OS: Windows
- Kubernetes version: 使用网盘下载的版本
- VirtualBox version: 6.0.10
- Vagrant version: 当且最新版本 2.2.5

## What I did?

Your operations on this repo.

## Messages
windows任务管理器有时会显示winnfsd 100% cpu使用率
Logs or error messages.
```
node1:
    node1: Removed:
    node1:   docker.x86_64 2:1.13.1-102.git7f2769b.el7.centos
    node1:   docker-client.x86_64 2:1.13.1-102.git7f2769b.el7.centos
    node1:   docker-common.x86_64 2:1.13.1-102.git7f2769b.el7.centos
    node1:
    node1: Installed:
    node1:   docker.x86_64 2:1.13.1-75.git8633870.el7.centos
    node1:   docker-client.x86_64 2:1.13.1-75.git8633870.el7.centos
    node1:   docker-common.x86_64 2:1.13.1-75.git8633870.el7.centos
    node1:
    node1: Complete!
    node1: Loaded plugins: fastestmirror
    node1: Loading mirror speeds from cached hostfile
    node1: Resolving Dependencies
    node1: --> Running transaction check
    node1: ---> Package etcd.x86_64 0:3.3.11-2.el7.centos will be installed
    node1: --> Finished Dependency Resolution
    node1:
    node1: Dependencies Resolved
    node1:
    node1: ================================================================================
    node1:  Package      Arch           Version                       Repository      Size
    node1: ================================================================================
    node1: Installing:
    node1:  etcd         x86_64         3.3.11-2.el7.centos           extras          10 M
    node1:
    node1: Transaction Summary
    node1: ================================================================================
    node1: Install  1 Package
    node1:
    node1: Total download size: 10 M
    node1: Installed size: 45 M
    node1: Downloading packages:
    node1: Running transaction check
    node1: Running transaction test
    node1: Transaction test succeeded
    node1: Running transaction
    node1:   Installing : etcd-3.3.11-2.el7.centos.x86_64                              1/1
    node1:
    node1:   Verifying  : etcd-3.3.11-2.el7.centos.x86_64                              1/1
    node1:
    node1:
    node1: Installed:
    node1:   etcd.x86_64 0:3.3.11-2.el7.centos
    node1:
    node1: Complete!
    node1: #[Member]
    node1: ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
    node1: ETCD_LISTEN_PEER_URLS="http://172.17.8.101:2380"
    node1: ETCD_LISTEN_CLIENT_URLS="http://172.17.8.101:2379,http://localhost:2379"
    node1: ETCD_NAME="node1"
    node1:
    node1: #[Clustering]
    node1: ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.17.8.101:2380"
    node1: ETCD_ADVERTISE_CLIENT_URLS="http://172.17.8.101:2379"
    node1: ETCD_INITIAL_CLUSTER="node1=http://172.17.8.101:2380"
    node1: ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
    node1: ETCD_INITIAL_CLUSTER_STATE="new"
    node1: create network config in etcd
    node1: start etcd...
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/etcd.service to /usr/lib/systemd/system/etcd.service.
    node1: create kubernetes ip range for flannel on 172.33.0.0/16
    node1: {"Network":"172.33.0.0/16","SubnetLen":24,"Backend":{"Type":"host-gw"}}
    node1: member 6ae27f9fa2984b1d is healthy: got healthy result from http://172.17.8.101:2379
    node1: cluster is healthy
    node1: /kube-centos
    node1: install flannel...
    node1: Loaded plugins: fastestmirror
    node1: Loading mirror speeds from cached hostfile
    node1: Resolving Dependencies
    node1: --> Running transaction check
    node1: ---> Package flannel.x86_64 0:0.7.1-4.el7 will be installed
    node1: --> Finished Dependency Resolution
    node1:
    node1: Dependencies Resolved
    node1:
    node1: ================================================================================
    node1:  Package          Arch            Version                 Repository       Size
    node1: ================================================================================
    node1: Installing:
    node1:  flannel          x86_64          0.7.1-4.el7             extras          7.5 M
    node1:
    node1: Transaction Summary
    node1: ================================================================================
    node1: Install  1 Package
    node1:
    node1: Total download size: 7.5 M
    node1: Installed size: 41 M
    node1: Downloading packages:
    node1: Running transaction check
    node1: Running transaction test
    node1: Transaction test succeeded
    node1: Running transaction
    node1:   Installing : flannel-0.7.1-4.el7.x86_64                                   1/1
    node1:
    node1:   Verifying  : flannel-0.7.1-4.el7.x86_64                                   1/1
    node1:
    node1:
    node1: Installed:
    node1:   flannel.x86_64 0:0.7.1-4.el7
    node1:
    node1: Complete!
    node1: create flannel config file...
    node1: enable flannel with host-gw backend
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/flanneld.service to /usr/lib/systemd/system/flanneld.service.
    node1: Created symlink from /etc/systemd/system/docker.service.wants/flanneld.service to /usr/lib/systemd/system/flanneld.service.
    node1: enable docker
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.

    node1: copy pem, token files
    node1: kubernetes/
    node1: kubernetes/LICENSES
```
